// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(otto_ffiFFI)
import otto_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_otto_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_otto_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureOttoFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol ModelManagerProtocol: AnyObject, Sendable {
    
    /**
     * Get the name of the currently active model.
     */
    func currentModel()  -> String
    
    /**
     * Get info for a specific model.
     */
    func getModel(name: String)  -> ModelInfo?
    
    /**
     * List all available models and their download status.
     */
    func listModels()  -> [ModelInfo]
    
    /**
     * Mark a model as downloaded.
     */
    func markDownloaded(name: String)  -> Bool
    
    /**
     * Set the current active model.
     */
    func setCurrentModel(name: String)  -> Bool
    
}
open class ModelManager: ModelManagerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_otto_ffi_fn_clone_modelmanager(self.handle, $0) }
    }
    /**
     * Default constructor.
     */
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_otto_ffi_fn_constructor_modelmanager_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_otto_ffi_fn_free_modelmanager(handle, $0) }
    }

    

    
    /**
     * Get the name of the currently active model.
     */
open func currentModel() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_otto_ffi_fn_method_modelmanager_current_model(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get info for a specific model.
     */
open func getModel(name: String) -> ModelInfo?  {
    return try!  FfiConverterOptionTypeModelInfo.lift(try! rustCall() {
    uniffi_otto_ffi_fn_method_modelmanager_get_model(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),$0
    )
})
}
    
    /**
     * List all available models and their download status.
     */
open func listModels() -> [ModelInfo]  {
    return try!  FfiConverterSequenceTypeModelInfo.lift(try! rustCall() {
    uniffi_otto_ffi_fn_method_modelmanager_list_models(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Mark a model as downloaded.
     */
open func markDownloaded(name: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_otto_ffi_fn_method_modelmanager_mark_downloaded(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),$0
    )
})
}
    
    /**
     * Set the current active model.
     */
open func setCurrentModel(name: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_otto_ffi_fn_method_modelmanager_set_current_model(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeModelManager: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ModelManager

    public static func lift(_ handle: UInt64) throws -> ModelManager {
        return ModelManager(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ModelManager) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ModelManager {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ModelManager, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModelManager_lift(_ handle: UInt64) throws -> ModelManager {
    return try FfiConverterTypeModelManager.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModelManager_lower(_ value: ModelManager) -> UInt64 {
    return FfiConverterTypeModelManager.lower(value)
}




/**
 * Result of a code reshape operation.
 */
public struct CodeReshape: Equatable, Hashable {
    public var original: String
    public var reshaped: String
    public var operation: String
    public var confidence: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(original: String, reshaped: String, operation: String, confidence: Float) {
        self.original = original
        self.reshaped = reshaped
        self.operation = operation
        self.confidence = confidence
    }

    

    
}

#if compiler(>=6)
extension CodeReshape: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCodeReshape: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CodeReshape {
        return
            try CodeReshape(
                original: FfiConverterString.read(from: &buf), 
                reshaped: FfiConverterString.read(from: &buf), 
                operation: FfiConverterString.read(from: &buf), 
                confidence: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: CodeReshape, into buf: inout [UInt8]) {
        FfiConverterString.write(value.original, into: &buf)
        FfiConverterString.write(value.reshaped, into: &buf)
        FfiConverterString.write(value.operation, into: &buf)
        FfiConverterFloat.write(value.confidence, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCodeReshape_lift(_ buf: RustBuffer) throws -> CodeReshape {
    return try FfiConverterTypeCodeReshape.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCodeReshape_lower(_ value: CodeReshape) -> RustBuffer {
    return FfiConverterTypeCodeReshape.lower(value)
}


/**
 * A completion suggestion for a given prefix.
 */
public struct Completion: Equatable, Hashable {
    public var prefix: String
    public var suggestion: String
    public var confidence: Float
    public var isMlBased: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(prefix: String, suggestion: String, confidence: Float, isMlBased: Bool) {
        self.prefix = prefix
        self.suggestion = suggestion
        self.confidence = confidence
        self.isMlBased = isMlBased
    }

    

    
}

#if compiler(>=6)
extension Completion: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompletion: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Completion {
        return
            try Completion(
                prefix: FfiConverterString.read(from: &buf), 
                suggestion: FfiConverterString.read(from: &buf), 
                confidence: FfiConverterFloat.read(from: &buf), 
                isMlBased: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Completion, into buf: inout [UInt8]) {
        FfiConverterString.write(value.prefix, into: &buf)
        FfiConverterString.write(value.suggestion, into: &buf)
        FfiConverterFloat.write(value.confidence, into: &buf)
        FfiConverterBool.write(value.isMlBased, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletion_lift(_ buf: RustBuffer) throws -> Completion {
    return try FfiConverterTypeCompletion.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletion_lower(_ value: Completion) -> RustBuffer {
    return FfiConverterTypeCompletion.lower(value)
}


/**
 * Result of a grammar check.
 */
public struct GrammarCheck: Equatable, Hashable {
    public var original: String
    public var corrected: String
    public var suggestions: [String]
    public var confidence: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(original: String, corrected: String, suggestions: [String], confidence: Float) {
        self.original = original
        self.corrected = corrected
        self.suggestions = suggestions
        self.confidence = confidence
    }

    

    
}

#if compiler(>=6)
extension GrammarCheck: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGrammarCheck: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GrammarCheck {
        return
            try GrammarCheck(
                original: FfiConverterString.read(from: &buf), 
                corrected: FfiConverterString.read(from: &buf), 
                suggestions: FfiConverterSequenceString.read(from: &buf), 
                confidence: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: GrammarCheck, into buf: inout [UInt8]) {
        FfiConverterString.write(value.original, into: &buf)
        FfiConverterString.write(value.corrected, into: &buf)
        FfiConverterSequenceString.write(value.suggestions, into: &buf)
        FfiConverterFloat.write(value.confidence, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGrammarCheck_lift(_ buf: RustBuffer) throws -> GrammarCheck {
    return try FfiConverterTypeGrammarCheck.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGrammarCheck_lower(_ value: GrammarCheck) -> RustBuffer {
    return FfiConverterTypeGrammarCheck.lower(value)
}


/**
 * Information about an AI model.
 */
public struct ModelInfo: Equatable, Hashable {
    public var name: String
    public var repoId: String
    public var sizeGb: Double
    public var params: UInt32
    public var quantization: String
    public var isDownloaded: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, repoId: String, sizeGb: Double, params: UInt32, quantization: String, isDownloaded: Bool) {
        self.name = name
        self.repoId = repoId
        self.sizeGb = sizeGb
        self.params = params
        self.quantization = quantization
        self.isDownloaded = isDownloaded
    }

    

    
}

#if compiler(>=6)
extension ModelInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeModelInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ModelInfo {
        return
            try ModelInfo(
                name: FfiConverterString.read(from: &buf), 
                repoId: FfiConverterString.read(from: &buf), 
                sizeGb: FfiConverterDouble.read(from: &buf), 
                params: FfiConverterUInt32.read(from: &buf), 
                quantization: FfiConverterString.read(from: &buf), 
                isDownloaded: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ModelInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.repoId, into: &buf)
        FfiConverterDouble.write(value.sizeGb, into: &buf)
        FfiConverterUInt32.write(value.params, into: &buf)
        FfiConverterString.write(value.quantization, into: &buf)
        FfiConverterBool.write(value.isDownloaded, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModelInfo_lift(_ buf: RustBuffer) throws -> ModelInfo {
    return try FfiConverterTypeModelInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModelInfo_lower(_ value: ModelInfo) -> RustBuffer {
    return FfiConverterTypeModelInfo.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCompletion: FfiConverterRustBuffer {
    typealias SwiftType = Completion?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCompletion.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCompletion.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeModelInfo: FfiConverterRustBuffer {
    typealias SwiftType = ModelInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeModelInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeModelInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeModelInfo: FfiConverterRustBuffer {
    typealias SwiftType = [ModelInfo]

    public static func write(_ value: [ModelInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeModelInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ModelInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [ModelInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeModelInfo.read(from: &buf))
        }
        return seq
    }
}
/**
 * Check grammar in a piece of text and return corrections.
 */
public func checkGrammar(text: String) -> GrammarCheck  {
    return try!  FfiConverterTypeGrammarCheck_lift(try! rustCall() {
    uniffi_otto_ffi_fn_func_check_grammar(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Get a completion suggestion for the given text prefix.
 */
public func getCompletion(text: String) -> Completion?  {
    return try!  FfiConverterOptionTypeCompletion.lift(try! rustCall() {
    uniffi_otto_ffi_fn_func_get_completion(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Get all suggestions for a prefix.
 */
public func getCompletionSuggestions(text: String) -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_otto_ffi_fn_func_get_completion_suggestions(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Initialize the completion dictionary.
 */
public func initializeCompletions()  {try! rustCall() {
    uniffi_otto_ffi_fn_func_initialize_completions($0
    )
}
}
/**
 * Reshape code by applying a transformation.
 */
public func reshapeCode(code: String, operation: String) -> CodeReshape  {
    return try!  FfiConverterTypeCodeReshape_lift(try! rustCall() {
    uniffi_otto_ffi_fn_func_reshape_code(
        FfiConverterString.lower(code),
        FfiConverterString.lower(operation),$0
    )
})
}
/**
 * Get the backend version.
 */
public func version() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_otto_ffi_fn_func_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_otto_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_otto_ffi_checksum_func_check_grammar() != 59598) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_otto_ffi_checksum_func_get_completion() != 20158) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_otto_ffi_checksum_func_get_completion_suggestions() != 19006) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_otto_ffi_checksum_func_initialize_completions() != 26365) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_otto_ffi_checksum_func_reshape_code() != 33223) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_otto_ffi_checksum_func_version() != 28116) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_otto_ffi_checksum_method_modelmanager_current_model() != 65285) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_otto_ffi_checksum_method_modelmanager_get_model() != 9767) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_otto_ffi_checksum_method_modelmanager_list_models() != 27578) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_otto_ffi_checksum_method_modelmanager_mark_downloaded() != 59290) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_otto_ffi_checksum_method_modelmanager_set_current_model() != 15728) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_otto_ffi_checksum_constructor_modelmanager_new() != 6131) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureOttoFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all