import Foundation

/// EqSwift — Rust-to-Swift FFI bindings
///
/// This package wraps the Rust `eqswift` library via UniFFI-generated bindings.
///
/// The actual Swift types and FFI glue are generated by running:
///
/// ```bash
/// cargo run --bin uniffi-bindgen generate \
///   --library target/debug/libeqswift.dylib \
///   --language swift --out-dir eq-swift/swift/Generated
/// ```
///
/// Then copy or symlink the generated files into this target:
/// - `eqswift.swift`         → `Sources/EqSwift/eqswift.swift`
/// - `eqswiftFFI.h`          → `Sources/EqSwift/include/eqswiftFFI.h`
/// - `eqswiftFFI.modulemap`  → `Sources/EqSwift/include/module.modulemap`
///
/// # Example usage
///
/// ```swift
/// import EqSwift
///
/// let sum = add(a: 1, b: 2)                // 3
/// let greeter = Greeter()                   // constructor
/// let msg = greeter.greet(name: "World")   // "Hello, World!"
/// let person = Person(name: "Alice", age: 30)
/// let msg2 = greeter.greetPerson(person: person)
/// ```
public enum EqSwift {}

// NOTE: The generated UniFFI bindings (eqswift.swift, eqswiftFFI.h, etc.)
// should be placed in Sources/EqSwift/ alongside this file.
// They are not committed to version control because they are regenerated
// from the Rust library on every build.
